In [2]:
import pandas as pd
import numpy as np



In [3]:
from IPython.display import display

# Create a new dataset
new_dataset = pd.DataFrame({
    'Name': ['John', 'Jane', 'Doe'],
    'Age': [28, 34, 45],
    'Birthday': ['1995-05-15', '1989-08-22', '1978-12-01']
})

# Print the dataset
# Display the dataset in a table
display(new_dataset)



Name  Age    Birthday
0  John   28  1995-05-15
1  Jane   34  1989-08-22
2   Doe   45  1978-12-01

In [4]:
print(new_dataset)

   Name  Age    Birthday
0  John   28  1995-05-15
1  Jane   34  1989-08-22
2   Doe   45  1978-12-01


In [5]:
from datetime import datetime

# Calculate John's age
john_birthday = datetime.strptime('1978-12-01', '%Y-%m-%d')
current_date = datetime.now()
john_age = current_date.year - john_birthday.year - ((current_date.month, current_date.day) < (john_birthday.month, john_birthday.day))

print(f"John's age is {john_age}")

John's age is 46


In [6]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("amansingh0000000/smartphones")

print("Path to dataset files:", path)



/Users/admin/Documents/Projects/.venv/lib/python3.9/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(
/Users/admin/Documents/Projects/.venv/lib/python3.9/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


Path to dataset files: /Users/admin/.cache/kagglehub/datasets/amansingh0000000/smartphones/versions/1


In [15]:
import pandas as pd
import os
import kagglehub


# Download latest version
data_path = kagglehub.dataset_download("amansingh0000000/smartphones")

smartphones_csv = os.path.join(data_path, "mobile_phones_2000.csv")
df = pd.read_csv(smartphones_csv)
df.head(10)




Brand               Model  Price (USD)  Selling Platform  Rating  \
0  OnePlus       Narzo Edge 16      1286.64          Best Buy     3.5   
1     Sony        Pixel Max 24       728.52              eBay     4.6   
2  Samsung        Reno Plus 23      1086.68    Official Store     3.4   
3    Apple  Redmi Note Mini 16      1158.78    Official Store     3.5   
4     Vivo    P Series Edge 13      1656.05  Reliance Digital     4.9   
5     Vivo      P Series 5G 19       390.46          Best Buy     4.4   
6     Sony   Galaxy S Ultra 22      1172.46          Best Buy     3.2   
7    Apple         Reno Pro 20      1770.77            Amazon     3.3   
8    Nokia     Xperia Ultra 19       492.29            Amazon     3.7   
9   Realme    P Series Mini 19       730.09              eBay     4.2   

   Refresh Rate (Hz)  Screen Size (inches)  RAM (GB)  Storage (GB)  \
0                165                   7.2        16           128   
1                 90                   6.1         4            64   
2                 60                   6.2        12            64   
3                120                   7.1         6           128   
4                165                   6.1         8           512   
5                165                   6.5        12           512   
6                120                   6.5         8           256   
7                165                   5.5         8          1024   
8                 90                   7.4         4           256   
9                144                   6.1        16           128   

             Processor        Camera Setup  
0  Snapdragon 8+ Gen 1   12MP + 16MP + 5MP  
1        Dimensity 920    48MP + 8MP + 5MP  
2          Exynos 2200  200MP + 12MP + 8MP  
3           A16 Bionic   50MP + 50MP + 2MP  
4            Helio G99   64MP + 50MP + 8MP  
5        Dimensity 920   48MP + 50MP + 8MP  
6        Dimensity 920    12MP + 8MP + 2MP  
7           A16 Bionic   12MP + 12MP + 2MP  
8            Helio G99   12MP + 12MP + 2MP  
9        Dimensity 920   50MP + 12MP + 5MP

In [16]:
df.columns

Index(['Brand', 'Model', 'Price (USD)', 'Selling Platform', 'Rating',
       'Refresh Rate (Hz)', 'Screen Size (inches)', 'RAM (GB)', 'Storage (GB)',
       'Processor', 'Camera Setup'],
      dtype='object')

In [8]:
# Group by selling platform and calculate the count of entries for each platform
platform_grouped = df.groupby('Selling Platform').size().reset_index(name='Count').sort_values(by='Count', ascending=False)



# Display the grouped dataframe
platform_grouped

Selling Platform  Count
6           Walmart    260
0        AliExpress    258
4    Official Store    256
3          Flipkart    251
1            Amazon    250
7              eBay    247
5  Reliance Digital    244
2          Best Buy    234

In [9]:
unique_platforms_count = df['Selling Platform'].nunique()
print(f"Number of unique selling platforms: {unique_platforms_count}")

Number of unique selling platforms: 8


In [10]:
platform_model_count = df.groupby('Selling Platform')['Model'].nunique().reset_index(name='Model Count')
model_grouped = df.groupby('Model').size().reset_index(name='Count').sort_values(by='Count', ascending=False)
# Display the new dataframe
platform_model_count

Selling Platform  Model Count
0        AliExpress          246
1            Amazon          228
2          Best Buy          220
3          Flipkart          228
4    Official Store          239
5  Reliance Digital          225
6           Walmart          234
7              eBay          231

In [11]:
model_grouped

Model  Count
645      Pixel Edge 17      6
482       Nord Plus 14      5
131       Mate Edge 25      5
288      Moto G Pro 13      5
533      Nord Ultra 24      5
..                 ...    ...
553   P Series Lite 10      1
554   P Series Lite 13      1
555   P Series Lite 17      1
558   P Series Lite 21      1
619  P Series Turbo 21      1

[1238 rows x 2 columns]

In [12]:
model_platform_count = df.groupby(['Selling Platform', 'Brand']).size().reset_index(name='Count')
top_5_platforms = platform_grouped.head(5)['Selling Platform']
model_platform_count = model_platform_count[model_platform_count['Selling Platform'].isin(top_5_platforms)]
# Sort the resulting dataframe by 'Count' in descending order
model_platform_count = model_platform_count.sort_values(by='Count', ascending=False)
model_platform_count

Selling Platform     Brand  Count
18           Amazon      Oppo     35
56   Official Store   Samsung     33
80          Walmart   Samsung     32
8        AliExpress   Samsung     29
73          Walmart    Google     29
7        AliExpress    Realme     28
52   Official Store     Nokia     27
77          Walmart   OnePlus     26
55   Official Store    Realme     25
11       AliExpress    Xiaomi     25
72          Walmart     Apple     25
47         Flipkart    Xiaomi     25
12           Amazon     Apple     24
79          Walmart    Realme     24
36         Flipkart     Apple     23
38         Flipkart    Huawei     23
15           Amazon  Motorola     23
41         Flipkart   OnePlus     23
44         Flipkart   Samsung     23
13           Amazon    Google     23
74          Walmart    Huawei     23
6        AliExpress      Oppo     23
2        AliExpress    Huawei     23
14           Amazon    Huawei     22
53   Official Store   OnePlus     22
51   Official Store  Motorola     22
49   Official Store    Google     22
46         Flipkart      Vivo     22
40         Flipkart     Nokia     22
83          Walmart    Xiaomi     22
0        AliExpress     Apple     21
9        AliExpress      Sony     21
16           Amazon     Nokia     21
22           Amazon      Vivo     21
50   Official Store    Huawei     20
43         Flipkart    Realme     19
20           Amazon   Samsung     19
3        AliExpress  Motorola     19
78          Walmart      Oppo     19
10       AliExpress      Vivo     19
42         Flipkart      Oppo     19
39         Flipkart  Motorola     19
23           Amazon    Xiaomi     18
81          Walmart      Sony     18
1        AliExpress    Google     18
58   Official Store      Vivo     18
37         Flipkart    Google     17
54   Official Store      Oppo     17
57   Official Store      Sony     17
59   Official Store    Xiaomi     17
48   Official Store     Apple     16
5        AliExpress   OnePlus     16
17           Amazon   OnePlus     16
4        AliExpress     Nokia     16
45         Flipkart      Sony     16
19           Amazon    Realme     16
82          Walmart      Vivo     16
75          Walmart  Motorola     15
21           Amazon      Sony     12
76          Walmart     Nokia     11

In [18]:
screen_size_average = df['Screen Size (inches)'].mean()

print(screen_size_average)

6.26825


In [19]:
price_average = df['Price (USD)'].mean()
print(price_average)



1085.49698


In [23]:
price_average_by_platform = df.groupby('Selling Platform')['Price (USD)'].mean().reset_index(name='Average Price (USD)')
# Sort the resulting dataframe by 'Average Price (USD)' in descending order
price_average_by_group = price_average_by_platform.sort_values(by='Average Price (USD)', ascending=False)
print(price_average_by_platform)

   Selling Platform  Average Price (USD)
0        AliExpress          1030.117248
1            Amazon          1097.568400
2          Best Buy          1066.216026
3          Flipkart          1081.012510
4    Official Store          1092.117266
5  Reliance Digital          1109.923279
6           Walmart          1059.466385
7              eBay          1150.357733


In [5]:
price_average_by_brand = df.groupby('Brand')['Price (USD)'].mean().reset_index(name='Average Price (USD)')
price_average_by_brand = price_average_by_brand.sort_values(by='Average Price (USD)', ascending=False)
print(price_average_by_brand)

NameError: name 'df' is not defined

In [6]:
import numpy as np

In [21]:
np.sum((0 < a) & (a < 10))


np.int64(185)

In [50]:
ar = np.array([[1, 2, 3, 4, 5], [2, 2,3,3,5]])
print(ar)

[[1 2 3 4 5]
 [2 2 3 3 5]]


In [47]:
second_row = ar[1]
print(second_row)

[2 2 3 3 5]


In [49]:
for x in ar:
    if (second_row > x):
        a += x
print(a)

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [31]:
print(ar[:,-2])

[4 4]


In [40]:
print(ar[1,:])


[2 2 3 3 5]


In [41]:
def column_comparison(two_d_array):
    for x in two_d_array:
        a += (two_d_array[-2,:] < x)
    return a 


In [52]:
arr = np.array([10, 20, 30, 40, 50])
arr[:3]



array([10, 20, 30])

In [53]:
arr = np.array([10, 20, 30, 40, 50])
arr[-2:]

array([40, 50])

In [54]:
arr[arr>30]

array([40, 50])

In [57]:
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])
arr[1]

array([4, 5, 6])

In [60]:
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])
arr[:,0]

array([1, 4, 7])

In [63]:
arr = np.array([[10, 20, 30, 40],
                [50, 60, 70, 80],
                [90, 100, 110, 120]])
arr[:2,:2]


array([[10, 20],
       [50, 60]])

In [65]:
arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12]])
arr[-2:,-2:]

array([[ 7,  8],
       [11, 12]])

In [67]:
arr = np.array([100, 200, 300, 400, 500])
arr[[1,3,4]]

array([200, 400, 500])

In [68]:
arr = np.array([15, 25, 35, 45, 55])
arr[arr > 30] 

array([35, 45, 55])

In [69]:
arr = np.array([0, 10, 20, 30, 40, 50, 60])
arr[1::2]

array([10, 30, 50])

In [77]:
arr = np.array([[10, 20, 30],
                [40, 50, 60],
                [70, 80, 90]])
arr[1,::-1]

array([60, 50, 40])

In [83]:
arr = np.array([12, 15, 18, 21, 24, 27])
arr[(arr % 3 == 0) & ( arr % 6 !=0)]

array([15, 21, 27])

In [84]:
arr = np.array([[5, 10, 15],
                [20, 25, 30],
                [35, 40, 45]])
arr[arr > 20]

array([25, 30, 35, 40, 45])

In [85]:
arr = np.array([[3, 6, 9],
                [12, 15, 18],
                [21, 24, 27]])
arr[(arr % 2 == 0) & (arr > 10)]

array([12, 18, 24])

In [87]:
arr = np.array([2, 4, 6, 8, 10])
arr[arr > 5] = 0
print(arr)

[2 4 0 0 0]


In [88]:
arr = np.array([[100, 150, 200],
                [250, 300, 350],
                [400, 450, 500]])
arr[arr % 100 == 0] = -1
print(arr)

[[ -1 150  -1]
 [250  -1 350]
 [ -1 450  -1]]


In [89]:
arr = np.array([1, 4, 9, 16, 25, 36, 49, 64])
arr[(arr % 2 != 0)]

array([ 1,  9, 25, 49])

In [90]:
arr = np.array([[5, 10, 15],
                [20, 25, 30],
                [35, 40, 45]])
#Task: Select all elements greater than 10 and less than or equal to 40, but exclude any number divisible by 15.
arr[(arr > 10) & (arr <= 40) & (arr % 15 != 0)]

array([20, 25, 35, 40])

In [107]:
arr = np.array([[10, 20, 30],
                [40, 50, 60],
                [70, 80, 90]])
arr[::2,:][arr[::2,:] > 25]


array([30, 70, 80, 90])

In [114]:
arr = np.array([[3, 6, 9],
                [12, 15, 18],
                [21, 24, 27]])
arr[::2,::2]

array([[ 3,  9],
       [21, 27]])

In [125]:
arr = np.array([
        [1, 5, 3, 4],
        [2, 8, 7, 6],
        [3, 1, 4, 2],
        [4, 9, 2, 10]
    ])

In [124]:
def column_comparison(arr):
    # Compare second column with second last column
    condition = arr[:, 1] > arr[:, -2]
    return arr[condition]
    

In [127]:
data = np.array([
    [8, 9, 3, 8, 8],
    [0, 5, 3, 9, 9],
    [5, 7, 6, 0, 4],
    [7, 8, 1, 6, 2],
    [2, 1, 3, 5, 8]
])
column_comparison(data)

array([[8, 9, 3, 8, 8],
       [5, 7, 6, 0, 4],
       [7, 8, 1, 6, 2]])

In [128]:
data

array([[8, 9, 3, 8, 8],
       [0, 5, 3, 9, 9],
       [5, 7, 6, 0, 4],
       [7, 8, 1, 6, 2],
       [2, 1, 3, 5, 8]])

In [129]:
data[[1,3,2]]

array([[0, 5, 3, 9, 9],
       [7, 8, 1, 6, 2],
       [5, 7, 6, 0, 4]])